<?php
/** @var \OH\TopHeaderAlert\ViewModel\TopAlert $viewModel */
$viewModel = $block->getViewModel();
$elements = $viewModel->getElements();
$backColor = $viewModel->getBackgroundColor();
$textColor = $viewModel->getTextColor();
?>

<?php if ($viewModel->getIsEnabled() && $elements): ?>
    <div class="oh-top-wrapper" <?= $backColor ? sprintf('style="background-color: %s"', $backColor) : '' ?>>
        <span class="close"></span>
        <ul class="items">
            <?php foreach ($elements as $element): ?>
                <span class="item" <?= $textColor ? sprintf('style="color: %s"', $textColor) : '' ?>><?= $element['text'] ?></span>
            <?php endforeach; ?>
        </ul>
    </div>
    <script type="text/x-magento-init">
        {
            ".oh-top-wrapper": {
                "OH_TopHeaderAlert/js/view/slickenize": {
                    "props": "<?=$escaper->escapeJs($viewModel->getSlickProps())?>"
                }
            }
        }
    </script>
<?php endif; ?>